### ISSUE TITLE
Joint position and effort limits

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-physics#14]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/issues/14)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
# Summary

We should add a feature for Joint limits (position, velocity, acceleration, effort). I would make them separate features in case a physics engine doesn't implement them all.

# Motivation

This is needed for the MotionTimerLockJoints plugin.

# Describe alternatives you've considered

none

# Additional context

**Comment by peci1** [comment]
Aren't these implemented already?

**Comment by azeey** [comment]
Closing this since joint limits are already available in DART.
