### ISSUE TITLE
Annoying GenericJoint::setRestPosition DART warning 

### ISSUE THREAD

**Issue by diegoferigo** [gazebosim/gz-physics#68]
I am running fairly long simulations (~days) and the log is flooded with warnings like the following:

```
Warning [GenericJoint.hpp:1473] [GenericJoint::setRestPosition] Value of _q0 [0], is out of the limit range [0.261799, 1.85005] for index [0] of Joint [Joint].
```

There is no way to suppress it since it's related to the DART logger. In https://github.com/dartsim/dart/issues/869#issuecomment-291660477 some more details about the warning. 

Anyway, this warning has been removed in the upstream repository in https://github.com/dartsim/dart/pull/1418, but the DART packages in the osrf repository does not seem to include this fix. If I recall, you use the [azeey/dart](https://github.com/azeey/dart) fork for packaging, that is a bit behind upstream.

Waiting https://github.com/ignitionrobotics/ign-physics/issues/49, would it be possible to have this upstream PR merged in the next release? @azeey @j-rivero

**Comment by scpeters** [comment]
that sounds reasonable to me

**Comment by azeey** [comment]
Since we're now mostly using upstream DART with 6.12 and later, I think it's safe to close this.
