### ISSUE TITLE
Add Feature to allow runtime changes to joint limits

### ISSUE THREAD

**Issue by peci1** [gazebosim/gz-physics#96]
I'd like to change `<limit><velocity>` and `<limit><effort>` dynamically during the simulation. Currently, it seems that these values are only read when parsing the model.

I've tried this, but changing the component data has no effect:

```c++
auto axisComponent = _ecm.Component<components::JointAxis>(this->joint);
axisComponent->Data().SetEffort(2.0);
```

I also tried re-creating the component, but that also doesn't change the physics engine behavior:

```c++
auto axisComponent = _ecm.Component<components::JointAxis>(this->joint);
axisComponent->Data().SetEffort(torque);
components::JointAxis axis(axisComponent->Data());
*axisComponent = axis;
```

**Comment by scpeters** [comment]
Your code snippets are from ign-gazebo, but this is an issue with ign-physics because there is no `Feature` that exposes joint limits via the API.

**Comment by scpeters** [comment]
I think a `Feature` API could be added to [Joint.hh](https://github.com/ignitionrobotics/ign-physics/blob/master/include/ignition/physics/Joint.hh)

**Comment by scpeters** [comment]
feature was added in #260
